import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/src/providers/query-provider";
import { Toaster } from "react-hot-toast";
// TODO: Agregar meta data
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body suppressHydrationWarning>
        <QueryProvider>{children}</QueryProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}

